-- ============================================================
-- BraidedbyAGB — schema migrations
--
-- ⚠️  THIS FILE IS NO LONGER THE SOURCE OF TRUTH — AND IS NOT RUN.
--
-- All schema migrations now live in ONE place:  database/migrate.php
-- It applies every change idempotently (each step checks whether it is
-- already applied), so it is safe to run as many times as you like and it
-- can bring a fresh database (built from schema.sql) fully up to date on
-- its own.
--
--   Apply (web):  https://braidedbyagb.co.uk/database/migrate.php?key=YOUR_SECRET
--   Apply (CLI):  php database/migrate.php
--
-- ➡️  To add a NEW migration: add a guarded step() to the bottom of
--     database/migrate.php. Do NOT add SQL here — nothing in this file is
--     executed, so anything added here would silently never apply (that
--     exact drift is what previously broke bookings).
--
-- The historical hand-run SQL that used to live in this file has been
-- ported in full into migrate.php and remains available in git history.
-- This stub is kept only so older links to the filename don't 404.
-- ============================================================
